# Generated by Django 4.2.7 on 2023-12-03 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('about', models.TextField(blank=True, null=True, verbose_name='درباره')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('image_manager', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر مدیر')),
                ('image_symbol', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر نماد')),
                ('image_about', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر درباره')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحات اصلی',
            },
        ),
    ]
