# Generated by Django 4.2.7 on 2023-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_options_remove_home_image_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_standard', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='نماد استاندارد')),
            ],
        ),
    ]
