# Generated by Django 4.2.7 on 2023-12-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'استاندارد', 'verbose_name_plural': 'استاندارد ها'},
        ),
        migrations.AddField(
            model_name='standard',
            name='tittle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع'),
        ),
    ]
