# Generated by Django 4.2.7 on 2023-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_standard_options_standard_tittle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_application', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع کاربرد')),
                ('application', models.TextField(blank=True, null=True, verbose_name='کاربرد')),
                ('tittle_process', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع فرایند')),
                ('process', models.TextField(blank=True, null=True, verbose_name='فرآیند')),
                ('tittle_manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع مدیر')),
                ('manager', models.TextField(blank=True, null=True, verbose_name='مدیر')),
                ('tittle_business', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع تجارت')),
                ('business', models.TextField(blank=True, null=True, verbose_name='تجارت')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
