# Generated by Django 4.2.7 on 2023-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر فرآیند'),
        ),
        migrations.AddField(
            model_name='contact',
            name='image_manager',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر مدیر'),
        ),
    ]
