# Generated by Django 4.2.7 on 2023-12-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_image_contact_image_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_application', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع کاربرد')),
                ('application', models.TextField(blank=True, null=True, verbose_name='کاربرد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر فرآیند')),
                ('tittle_process', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع فرایند')),
                ('process', models.TextField(blank=True, null=True, verbose_name='فرآیند')),
                ('tittle_manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع مدیر')),
                ('manager', models.TextField(blank=True, null=True, verbose_name='مدیر')),
                ('image_manager', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر مدیر')),
                ('tittle_business', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع تجارت')),
                ('business', models.TextField(blank=True, null=True, verbose_name='تجارت')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'پیغام', 'verbose_name_plural': 'پیغام ها'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='application',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='business',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image_manager',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='process',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tittle_application',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tittle_business',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tittle_manager',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tittle_process',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیغام'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن'),
        ),
    ]
