# Generated by Django 4.2.7 on 2023-12-13 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_about_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'information', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'standard', 'verbose_name_plural': 'standards'},
        ),
        migrations.AlterField(
            model_name='about',
            name='application',
            field=models.TextField(blank=True, null=True, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='about',
            name='business',
            field=models.TextField(blank=True, null=True, verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='process image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_manager',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='manager image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='manager',
            field=models.TextField(blank=True, null=True, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='about',
            name='process',
            field=models.TextField(blank=True, null=True, verbose_name='process'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tittle_application',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject of application'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tittle_business',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of business'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tittle_manager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the manager'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tittle_process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the process'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='home',
            name='attributes',
            field=models.TextField(blank=True, null=True, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_about',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='image about'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_manager',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='manager image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_symbol1',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='icon image 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_symbol2',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='icon image 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_symbol3',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='icon image 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='home',
            name='production',
            field=models.TextField(blank=True, null=True, verbose_name='production'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tittle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='home',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='image_standard',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='standard symbol'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='tittle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
    ]
