# Generated by Django 4.2.7 on 2023-12-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='application_en',
            field=models.TextField(blank=True, null=True, verbose_name='application'),
        ),
        migrations.AddField(
            model_name='about',
            name='application_fa',
            field=models.TextField(blank=True, null=True, verbose_name='application'),
        ),
        migrations.AddField(
            model_name='about',
            name='business_en',
            field=models.TextField(blank=True, null=True, verbose_name='business'),
        ),
        migrations.AddField(
            model_name='about',
            name='business_fa',
            field=models.TextField(blank=True, null=True, verbose_name='business'),
        ),
        migrations.AddField(
            model_name='about',
            name='manager_en',
            field=models.TextField(blank=True, null=True, verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='about',
            name='manager_fa',
            field=models.TextField(blank=True, null=True, verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='about',
            name='process_en',
            field=models.TextField(blank=True, null=True, verbose_name='process'),
        ),
        migrations.AddField(
            model_name='about',
            name='process_fa',
            field=models.TextField(blank=True, null=True, verbose_name='process'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_application_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject of application'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_application_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject of application'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_business_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of business'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_business_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of business'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_manager_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the manager'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_manager_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the manager'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_process_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the process'),
        ),
        migrations.AddField(
            model_name='about',
            name='tittle_process_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='the subject of the process'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_fa',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='home',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='home',
            name='about_fa',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='home',
            name='address_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='home',
            name='address_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='home',
            name='attributes_en',
            field=models.TextField(blank=True, null=True, verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='home',
            name='attributes_fa',
            field=models.TextField(blank=True, null=True, verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='home',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='home',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='home',
            name='production_en',
            field=models.TextField(blank=True, null=True, verbose_name='production'),
        ),
        migrations.AddField(
            model_name='home',
            name='production_fa',
            field=models.TextField(blank=True, null=True, verbose_name='production'),
        ),
        migrations.AddField(
            model_name='home',
            name='tittle_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='home',
            name='tittle_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='standard',
            name='tittle_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='standard',
            name='tittle_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subject'),
        ),
    ]
