# Generated by Django 4.2.7 on 2023-12-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_about_application_en_about_application_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='product name')),
                ('name_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='product name')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='product image')),
                ('image_packing', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='image of product packaging')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='wallpaper')),
            ],
            options={
                'verbose_name': 'wallpaper',
                'verbose_name_plural': 'wallpapers',
            },
        ),
    ]
